redis:
    image: redis:3.2.6
    container_name: redis

webserver:
    container_name: webserver
    image: nginx:1.11.6-alpine
    volumes:
        - ../token:/token
        - ./config/docker/${ENV}/site.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "8080:80"
    links:
        - php

php:
    container_name: php
    build: .
    dockerfile: ./config/docker/${ENV}/Dockerfile
    volumes:
        - ../token:/token
    expose:
        - "9000"
    links:
        - redis